package uz.bob.app_phone_purchases.entity.enums;

public enum Permission {

    ADD_USER, //ADMIN
    EDIT_USER,//ADMIN
    DELETE_USER,//ADMIN
    VIEW_USERS,//ADMIN
    ADD_ROLE,//ADMIN
    EDIT_ROLE,//ADMIN
    DELETE_ROLE,//ADMIN
    VIEW_ROLE,//ADMIN
//==8
    ADD_PHONE,//ADMIN,OPERATOR
    EDIT_PHONE,//ADMIN,OPERATOR
    DELETE_PHONE,//ADMIN,OPERATOR
    ADD_MAKER,//ADMIN,OPERATOR
    EDIT_MAKER,//ADMIN,OPERATOR
    DELETE_MAKER,//ADMIN,OPERATOR
    ADD_PHOTO,//ADMIN,OPERATOR
    EDIT_PHOTO,//ADMIN,OPERATOR
    DELETE_PHOTO,//ADMIN,OPERATOR
//==9
    VIEW_PURCHASES,//ADMIN
    DELETE_PURCHASES,//ADMIN


    VIEW_PHONE,//ALL

}
